# Configuration file of install.softwares(Non-Github)
title = "Non-Github Configuration File"
[gmap]
source_url = "http://research-pub.gene.com/gmap/src/{{version}}.tar.gz"

version_newest = "gmap-gsnap-2017-02-15"

version_available = ["gmap-gsnap-2017-02-15", "gmap-gsnap-2016-11-07", "gmap-gsnap-2016-09-14", "gmap-gsnap-2016-06-30.v5", "gmap-gsnap-2015-12-31.v10", "gmap-gsnap-2015-07-23", "gmap-gsnap-2014-12-31.v2", "gmap-gsnap-2014-10-22", "gmap-gsnap-2014-08-20", "gmap-gsnap-2014-06-10", "gmap-gsnap-2014-05-15.v3", "gmap-gsnap-2014-03-28.v2", "gmap-gsnap-2013-10-28", "gmap-gsnap-2013-09-30.v2", "gmap-gsnap-2013-03-31.v5", "gmap-gsnap-2012-07-20.v3", "gmap-gsnap-2012-04-27", "gmap-gsnap-2012-01-11", "gmap-gsnap-2011-12-28", "gmap-gsnap-2011-11-30", "gmap-gsnap-2011-10-16", "gmap-gsnap-2011-09-14", "gmap-gsnap-2011-03-28", "gmap-gsnap-2010-07-27", "gmap-gsnap-2010-03-09", "gmap-2007-09-28", "gmap-2007-06-04", "gmap-2006-12-18", "gmap-2006-04-21", "gmap-2005-10-25", "gmap-2005-07-15", "gmap-2005-06-23", "gmap-2005-05-20", "gmap-2005-05-06", "gmap-2005-03-11"]

after_failure = "echo 'fail!'"

after_success = "echo 'successful!'"

make_dir = ["./"]

bin_dir = ["./"]

[gmap.before_install]
linux = ""
mac = ""
windows = ""

[gmap.install]
linux = "./configure --prefix=`pwd` && make && make install"
mac = "sed -i s/\"## CFLAGS='-O3 -m64' .*\"/\"CFLAGS='-O3 -m64'\"/ config.site && ./configure --prefix=`pwd` && make && make install"
windows = "./configure --prefix=`pwd` && make && make install"

[annovar]
source_url = "http://www.openbioinformatics.org/annovar/download/0wgxR2rIVP/annovar.{{version}}.tar.gz"

version_newest = "latest"

version_available = ["latest"]

after_failure = "echo 'fail!'"

after_success = "echo 'successful!'"

make_dir = ["./"]

bin_dir = ["./"]

[annovar.before_install]
linux = ""
mac = ""
windows = ""

[annovar.install]
linux = ""
mac = ""
windows = ""

[htseq]
source_url = ["https://pypi.python.org/packages/3c/6e/f8dc3500933e036993645c3f854c4351c9028b180c6dcececde944022992/HTSeq-{{version}}.tar.gz",
"https://pypi.python.org/packages/72/0f/566afae6c149762af301a19686cd5fd1876deb2b48d09546dbd5caebbb78/HTSeq-{{version}}.tar.gz", "https://pypi.python.org/packages/7d/be/784905ab26e2b53dff8a65bcbc1321e5a3b4f894c1960c152f71e5fc791e/HTSeq-{{version}}-py2.7.exe"]

version_newest = "0.6.1p1"

version_available = ["0.6.1p1", "0.6.1", "0.6.1.win32"]

after_failure = "echo 'fail!'"

after_success = "echo 'successful!'"

make_dir = ["./"]

bin_dir = ["./scripts"]

[htseq.before_install]
linux = "pip install numpy"
mac = "pip install numpy"
windows = "pip install numpy"

[htseq.install]
linux = "python setup.py install"
mac = "python setup.py install"
windows = "HTSeq-{{version}}-py2.7.exe"

[gatk_bundle]
source_url = "ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/{{version}}/"

source_is.dir = true

version_newest = "hg38"

version_available = ["hg38", "hg19", "hg18", "b37", "b36"]

after_failure = "echo 'fail!'"

after_success = "echo 'successful!'"

make_dir = ["./"]

[gatk_bundle.before_install]
linux = ""
mac = ""
windows = ""

[gatk_bundle.install]
linux = ""
mac = ""
windows = ""

[hisat2_reffa]
source_url = "ftp://ftp.ccb.jhu.edu/pub/infphilo/hisat2/data/{{version}}.tar.gz"

version_newest = "grch38"

version_available = ["bdgp6", "bdgp6_tran", "ce10", "dm6", "grch37", "grch37_snp", "grch37_snp_tran", "grch37_snp_tran_ercc", "grch37_tran", "grch38", "grch38_snp", "grch38_snp_tran", "grch38_snp_tran_ercc", "grch38_tran", "grcm38", "grcm38_snp", "grcm38_snp_tran", "grcm38_snp_tran_ercc", "grcm38_tran", "hg19", "hg38", "hg38_snp_tran_oudejans", "hg38_tran", "mm10", "r64", "r64_tran", "rn6", "rn6_ercc", "rnor6", "sc3", "wbcel235", "wbcel235_tran", "zm3_snp_tran_ercc"]

after_failure = "echo 'fail!'"

after_success = "echo 'successful!'"

make_dir = ["./"]

[hisat2_reffa.before_install]
linux = ""
mac = ""
windows = ""

[hisat2_reffa.install]
linux = ""
mac = ""
windows = ""

[ucsc_reffa]
source_url = ["http://hgdownload.cse.ucsc.edu/goldenPath/{{version}}/bigZips/{{version}}.chromFa.tar.gz",
"http://hgdownload.cse.ucsc.edu/goldenPath/{{version}}/bigZips/chromFa.tar.gz"]

version_newest = "hg38"

version_available = ["hg19", "hg38"]

after_failure = "echo 'fail!'"

after_success = "echo 'successful!'"

make_dir = ["./"]

[ucsc_reffa.before_install]
linux = ""
mac = ""
windows = ""

[ucsc_reffa.install]
linux = ""
mac = ""
windows = ""

[ensemble_grch37_reffa]
source_url = "ftp://ftp.ensembl.org/pub/release-{{version}}/fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.{{version}}.dna.primary_assembly.fa.gz"

version_newest = "75"

version_available = ["75"]

after_failure = "echo 'fail!'"

after_success = "echo 'successful!'"

make_dir = ["./"]

[ensemble_grch37_reffa.before_install]
linux = ""
mac = ""
windows = ""

[ensemble_grch37_reffa.install]
linux = ""
mac = ""
windows = ""

[ensemble_grch38_reffa]
source_url = "ftp://ftp.ensembl.org/pub/release-{{version}}/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz"

version_newest = "87"

version_available = ["76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87"]

after_failure = "echo 'fail!'"

after_success = "echo 'successful!'"

make_dir = ["./"]

[ensemble_grch38_reffa.before_install]
linux = ""
mac = ""
windows = ""

[ensemble_grch38_reffa.install]
linux = ""
mac = ""
windows = ""

[edena]
source_url = ["http://www.genomic.ch/edena/{{version}}.tar.gz", "http://www.genomic.ch/edena/{{version}}.zip"]

version_newest = "EdenaV3.131028"

version_available = ["EdenaV3.131028", "EdenaV3.130110", "EdenaV3.121122", "Edena3dev120926_linux64", "Edena3Dev120626_linux64", "Edena3Dev120626_linux32", "Edena3Dev120615_linux64", "Edena3Dev120615_linux32", "Edena3Dev110920_linux64", "Edena3Dev110920_linux32", "Edena3Dev110815_linux64", "Edena3Dev110815_linux32", "Edena3Dev110814_linux64", "Edena3Dev110814_linux32", "Edena3Dev110705_linux64", "Edena3Dev110705_linux32", "edena2.1.1_linux32", "edena2.1.1_linux64", "edena2.1.1_windows"]

after_failure = "echo 'fail!'"

after_success = "echo 'successful!'"

make_dir = ["./"]

bin_dir = ["./bin"]

[edena.before_install]
linux = ""
mac = ""
windows = ""

[edena.install]
linux = "make"
mac = "make"
windows = "make"

[ucsc_utils]
source_url = "http://hgdownload.cse.ucsc.edu/admin/exe/userApps.{{version}}.src.tgz"

version_newest = "v344"

version_available = ["v305", "v306", "v307", "v308", "v309", "v310", "v311", "v312", "v313", "v314", "v315", "v316", "v317", "v318", "v319", "v320", "v321", "v322", "v323", "v324", "v325", "v326", "v327", "v328", "v329", "v330", "v331", "v332", "v333", "v334", "v335", "v336", "v337", "v338", "v339", "v340", "v341", "v342", "v343", "v344"]

after_failure = "echo 'fail!'"

after_success = "echo 'successful!'"

make_dir = ["./"]

bin_dir = ["./bin"]

[ucsc_utils.before_install]
linux = ""
mac = ""
windows = ""

[ucsc_utils.install]
linux = "make"
mac = "make"
windows = "make"

[fastqc]
source_url = ["http://www.bioinformatics.bbsrc.ac.uk/projects/fastqc/fastqc_v{{version}}.zip"]

version_newest = "0.11.5"

version_available = ["0.11.5", "0.11.4", "0.11.3", "0.11.2", "0.11.1", "0.10.1", "0.10.0", "0.9.6", "0.9.5", "0.9.4", "0.9.3", "0.9.2", "0.9.1", "0.9.0", "0.8.0", "0.7.2", "0.7.1", "0.7.0", "0.6.1", "0.6.0", "0.5.1", "0.5.0", "0.4.3", "0.4.2", "0.4.1", "0.4", "0.3.1", "0.3", "0.2", "0.1.1", "0.1"]

after_failure = "echo 'fail!'"

after_success = "echo 'successful!'"

make_dir = ["./"]

bin_dir = ["."]

[fastqc.before_install]
linux = ""
mac = ""
windows = ""

[fastqc.install]
linux = ""
mac = ""
windows = ""

[sqlite]
source_url = ["http://www.sqlite.org/2017/sqlite-autoconf-{{version}}.tar.gz", "http://www.sqlite.org/2016/sqlite-autoconf-{{version}}.tar.gz"]

version_newest = "3170000"

version_available = ["3170000", "3130000"]

after_failure = "echo 'fail!'"

after_success = "echo 'successful!'"

make_dir = ["./"]

bin_dir = ["./bin"]

[sqlite.before_install]
linux = "autoreconf -ivf"
mac = "autoreconf -ivf"
windows = "autoreconf -ivf"

[sqlite.install]
linux = "./configure --prefix=`pwd` && make && make install"
mac = "./configure --prefix=`pwd` && make && make install"
windows = "./configure --prefix=`pwd` && make && make install"


[cesa]
source_url = ["http://liulab.dfci.harvard.edu/CEAS/src/CEAS-Package-{{version}}.tar.gz"]

version_newest = "1.0.2"

version_available = ["1.0.2"]

after_failure = "echo 'fail!'"

after_success = "echo 'successful!'"

make_dir = ["./"]

bin_dir = ["./bin"]

[cesa.before_install]
linux = ""
mac = ""
windows = ""

[cesa.install]
linux = "python setup.py install"
mac = "python setup.py install"
windows = "python setup.py install"
