title = "A library of useful WEB URL resource."

[web.item.uniprot]
url = "http://www.uniprot.org/"
ftp = "ftp://ftp.uniprot.org/pub/databases/uniprot"

[web.item.kegg]
url = "http://www.kegg.jp/"
ftp = "ftp://ftp.genome.jp/pub"

[web.item.ncbi]
url = "https://www.ncbi.nlm.nih.gov/"
ftp = "ftp://ftp.ncbi.nih.gov/pub"

[web.item.ensembl]
url = "http://www.ensembl.org/"
ftp = "ftp://ftp.ensembl.org/pub/"

[web.item.tcga_gdc]
url = "https://portal.gdc.cancer.gov/search/s?facetTab=cases&filters=%7B%22op%22:%22and%22,%22content%22:%5B%7B%22op%22:%22in%22,%22content%22:%7B%22field%22:%22cases.project.program.name%22,%22value%22:%5B%22TCGA%22%5D%7D%7D%5D%7D"

[web.item.cbioportal]
url = 'http://www.cbioportal.org/index.do'

[web.item.rsnp3]
url = "http://rsnp3.psych.ac.cn/index.do"
ftp = "ftp://rv.psych.ac.cn/pub/rsnp3/"

